README.md

Documents the release process for this application for both non-production and production releases.
🔎 Nicer link to the new section: https://github.com/ministryofjustice/fala/blob/instructions-for-release/README.md#releasing
We will switch the default branch on this repository from `develop` to `master` once this is merged.

Document the staging and production release of the application

---

kubernetes_deploy/staging/deployment.yml

Extends the staging Kubernetes configuration to configure the https://github.com/ministryofjustice/laa-legal-adviser-api/ dependency.

Configure Legal Adviser API for staging

---

.circleci/config.yml
.circleci/define_build_environment_variables
.circleci/deploy_to_kubernetes
.circleci/notify_slack_channel
.circleci/tag_and_push_docker_image
Dockerfile
conf/uwsgi.ini
fala/settings/base.py
kubernetes_deploy/staging/deployment.yml
kubernetes_deploy/staging/ingress.yml
kubernetes_deploy/staging/service.yml
package.json

This pull request does the following:
- Configures the Docker image built in Circle CI build job to be pushed to AWS ECR
- Configures Kubernetes staging environment
- Deploy build to Kubernetes staging environment on successful build
- Notify Slack channel of successful deployment
- Optimise the Dockerfile
- Upgrade `node-sass`
For now, I've copied the helper Circle CI scripts from `cla_public`. The plan is to make these scripts, and others, available in a convenience Circle CI image after things have settled down a bit.
The current production instance, hosted via Template Deploy, the static assets are served from an S3 bucket. See https://github.com/ministryofjustice/fala/pull/11#issuecomment-429450104 for more info. Nginx also forwards requests received on port `80` to the python …

LGA-304 Run FALA on a staging Kubernetes namespace

---

.circleci/config.yml
.circleci/define_build_environment_variables
.circleci/deploy_to_kubernetes
.circleci/notify_slack_channel
.circleci/tag_and_push_docker_image
Dockerfile
Dockerfile.nginx
README.md
conf/nginx.conf
conf/uwsgi.ini
docker-compose.yml
fala/settings/local.example.py
kubernetes_deploy/staging/deployment.yml
kubernetes_deploy/staging/service.yml
package-lock.json

This pull request is the pre-cursor to getting nginx to serve static assets and front the Python web app in Kubernetes.
- `Dockerfile.nginx` builds the static assets and configures nginx.
- 'Dockerfile' still requires node because Django has dependency on jinja templates
- Python web app docker image is pushed to ECR repo `laa-get-access/laa-fala-webapp`
- nginx docker image is pushed to ECR repo `laa-get-access/laa-fala-nginx`
- Deploys nginx and webapp to Kubernetes
- Nginx has healthcheck at `/ping.json` that returns 200
- Local settings have been updated so static files are served during local development
- Use docker-compose for development of nginx<->webapp configuration (see readme)
The `tag_and_push_docker_image` script is simplified. It must be called with 2 positional arguments: …

Build and push nginx and webapp images to ECR

---

fala/apps/adviser/middleware.py
fala/settings/base.py
kubernetes_deploy/staging/deployment.yml

This pull requests configures Kubernetes to use liveness and readiness probes to determine the health of the web app container.
>Readiness and liveness probes can be used in parallel for the same container. Using both can ensure that traffic does not reach a container that is not ready for it, and that containers are restarted when they fail.
The kubelet will send the first readiness probe 5 seconds after the container starts. The kubelet will continue to run this check every 10 seconds until its ready. This application starts up quickly - it doesn't need to wait for anything to happen, e.g. load data.
The liveness probe is configured in the same way. If it cannot establish connection on TCP port 8000, Kubernetes will restart the container.
Initially, I added a `/ping.json` endpoint, …

LGA-316 Configure Kubernetes to use TCP liveness & readiness probe for webapp container

---

fala/settings/base.py
kubernetes_deploy/staging/deployment.yml
requirements/base.txt

This pull request configures the console handler to use the `logstash` formatter.
See the [comment I left in Jira](https://dsdmoj.atlassian.net/browse/LGA-299?focusedCommentId=60884&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-60884).
As describe in the Jira comment, the `mail_admins` handler has been removed.
This pull request originally attempted to replace the Raven client with [Sentry's Unified Python SDK](https://docs.sentry.io/quickstart?platform=python). However, there was trouble getting it working with correctly with uWSGI. Instead of tackling this in this PR, the upgrade from Raven to Sentry's Unified Python SDK will be deferred and can be done across all of our applications at the same time.
Sentry now has project set up for FALA staging. See …

Enable logstash formatter for console logs

---

.circleci/config.yml
README.md
fala/settings/base.py
kubernetes_deploy/production/deployment.yml
kubernetes_deploy/production/ingress.yml
kubernetes_deploy/production/service.yml
kubernetes_deploy/staging/deployment.yml

This pull request does the following:
- Configures Kubernetes production environment
- Allows deploys to Kubernetes production environment for `master` branch only
- Notify Slack channel of successful deployment to production
`ALLOWED_HOSTS` value is now retrieved from the environment, if available. When it's not, default values are used. The defaults are a temporary workaround until we stop using the legacy Template Deploy platform.

Configure Kubernetes production deploy

---

README.md
docs/development.md
docs/installation.md
docs/kubernetes.md
docs/releasing.md

This pull request adds a "Using Kubernetes" section to the README. See:
https://github.com/ministryofjustice/fala/blob/docs/README.md
It also breaks the README into separate files as it was getting a bit long.

LGA-306: Add "Use Kubernetes" documentation and split README into separate files 

---

.circleci/tag_and_push_docker_image
Dockerfile
fala/templates/base.html
fala/urls.py

At the moment, we are getting massive spam.
We are taking the feedback page offline until we implement proper spam filters.
The `docker push` will be retried 3 times as currently we are facing 504 errors from one of the older Docker registries and the retry is the accepted workaround until we can fully migrate to Kubernetes. (😭)
Reverts the removal of `/home/app/fala/static` folder in commit 564cc51e677a92ba32866ab0ffe3f15794fb59d4 as the folder is still required for template-deploy.

Disable feedback page (temporarily)

---

conf/nginx.conf
conf/uwsgi.ini

In the template-deploy world, the application runs in a Docker container but the nginx service is running on the host machine.
We don't know how to reconfigure the nginx server running on template-deploy to use the `uwsgi` protocol currently exposed, so I am taking the route of reverting the configuration to use the `http` protocol.
~~This will most likely **break** the Kubernetes configuration and it will have to be fixed.~~ Kubernetes configuration has also changed to reflect the same configuration.
Related: #22, #14

Expose uwsgi service on http protocol

---

.circleci/deploy_to_kubernetes
kubernetes_deploy/production/dashboard.yml
kubernetes_deploy/staging/dashboard.yml

For each display
- CPU utilisation %
- memory used GiB (cached GiB as well, if it makes any sense)
- memory %
- network receive & send MiB/s
- IO read & write MiB/s (may be a stretch goal)
- 
For each metric
- also displays red lines for hard limits for these metrics
- also displays yellow lines for soft (warning) limits for these metrics

LGA-397 - Setup pod monitoring for Kubernetes

---

.circleci/deploy_to_kubernetes
kubernetes_deploy/production/certificate.yml
kubernetes_deploy/production/ingress.yml
kubernetes_deploy/staging/certificate.yml
kubernetes_deploy/staging/ingress.yml

Enable TLS in the Ingress resource.
This was implicitly been done by the cloud platforms team before however recent changes mean that we need to explicitly do this

Enable TLS using new cloud platform spec

---

fala/templates/base.html

Explicitly sets postcode redacted location for GA before pageview send

LGA-47 Redact postcode from GA location before pageview send

---

conf/uwsgi.ini
fala/settings/production.py
kubernetes_deploy/production/deployment.yml
kubernetes_deploy/staging/deployment.yml

Added the following configuration to the kubernetes deployment:
SECRET_KEY
ZENDESK_API_USERNAME
ZENDESK_API_TOKEN
This includes changes to make the production application fail to boot without the required secrets. For production the DJANGO_SETTINGS_MODULE env var is set in the deployment.yml

LGA-458 - Review and copy required FALA configuration to Kubernetes

---

fala/templates/500.html

[Service is down designs ](https://docs.google.com/document/d/1XoybV_YCyrz2-K12r9cUtf7Z3EIsjNSoDbRSdBhjO_8/edit)
[LGA-487 Create a service offline page when FALA can't communicate with LALA API](https://dsdmoj.atlassian.net/browse/LGA-543)
This pull request changes the content of the service page offline message in FALA if backend or laalaa are down.
In order to view this service offline page paste the following code into fala/urls: 
```
if settings.DEBUG:
from django.views.defaults import server_error
urlpatterns += [
url(r'^500/$', server_error),
]
```
Then...
run locally, without running LALA or CLA backend,  adding '/500' at the end of the url that is generated. 

LGA-487 Service page offline fala

---

kubernetes_deploy/production/dashboard.yml

Update the dashboard label to match the new cloud platforms spec
Remove duplicate uuid
- [] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

Update the dashboard label to match the new cloud platforms spec

---

fala/templates/base.html

Addition of feedback / satisfaction link
Adds a link to a feedback form so users can give feedback on the FALA service
The link goes to a Google Form as we can't have a GOV.UK done survey, as the service is still in Alpha. 
LGA-571 add survey link to FALA

LGA-571 - add survey link to FALA

---

fala/apps/adviser/views.py
fala/settings/base.py
fala/settings/production.py
fala/templates/base.html
kubernetes_deploy/production/deployment.yml
kubernetes_deploy/staging/deployment.yml

Injects the api key into the env from kubernetes, on staging and
production
Defaults to the empty string when absent (which produces the existing
behaviour of warning dialogue and watermark when passed as the key)
Required.

LGA-148 - Use Google Maps API key from kubernetes

---

kubernetes_deploy/staging/deployment.yml

Configures `staging` deployments of the site to use the new domain for the staging instance of the legal adviser API, which is the kubernetes-deployed version.

LGA-587 - Update LAALAA_API_HOST env var on staging pods

---

.circleci/config.yml
Dockerfile
fala/apps/laalaa/api.py
requirements/base.txt

Fetch LAALAA provider categories from LAALAA endpoint instead of a local constant in this app
Downgrades pip to 18.1 due to cla_common packaging not being compatible with pip 19, see https://github.com/ministryofjustice/cla_public/pull/800 for more details
Requires https://github.com/ministryofjustice/laa-legal-adviser-api/pull/137 to be LAALAA master before merging in this PR

LGA-813 - Fetch LAALAA provider categories from LAALAA endpoint

---

kubernetes_deploy/production/deployment.yml

Start using Kubernetes cloud platform hosted LAALAA_API_HOST for production

LGA-634 - Start using Kubernetes cloud platform hosted LAALAA_API_HOST for production

---

fala/settings/production.py

Co-authored-by: Dávid Lantos <sldblog@users.noreply.github.com>
Make LAALAA_API_HOST setting required on production environment as suggested by @sldblog on https://github.com/ministryofjustice/fala/pull/42#discussion_r354374035

Make LAALAA_API_HOST setting required on production environment

---

fala/settings/base.py

This affects the expiry of presigned urls for static files included in the html using the static tag, eg the stylesheets themselves. These were defaulting to an hour, which was fine for page load but meant that pages left open in a browser and then returned to after the computer had been slept or restarted were loading without styling. This lengthens the expiry time to the maximum of a week to avoid that happening.

LGA-905 - Set week-long default expiry for staticfiles

---

fala/apps/adviser/forms.py
fala/assets-src/sass/main.scss
fala/templates/adviser/search.html
fala/templates/base.html
fala/templates/generic-py-base.html
fala/templates/macros/forms.html

Update tickboxes to GDS standard.
Used the smaller version tick boxes and arranged them in two columns (by element width).
Updated text entry boxes - this work will continue in LGA-1037.
Removed intrusive feedback link as per Rob's comments.
Corrected page layout with GDS classes.

LGA-1038 Tickboxes

---

fala/apps/adviser/forms.py
fala/templates/adviser/_results.html

New logic to isolate the towns from the addresses of all results and displays them in the sentence.
As part of this, we harmonize some place name variants so the same place isn't listed twice.  
Removes all-caps class `laa-postcode` for postcode field (it isn't solely for postcodes).
Adds in missing full stop from postcode and org name sentence (and elsewhere where it was missing).

LGA-1064 town missing from sentence bug

---

fala/assets-src/sass/_google-translate.scss
fala/templates/adviser/_results.html

Google translate field:
- makes drop-down GDS-like
- makes link highlight in the new GDS colour
- hides all non-British languages (like Chinese) so Welsh is easier to select
Postcode warnings:
- adds in warnings for non-English or Welsh postcodes.
- also adds in warnings for crown dependency postcodes if no postcode returned (in addition to the main method - just in case the postcode data is expanded to include these places in the future as it has done previously).

LGA-1037 Input fields style update

---

fala/assets-src/sass/_fala-results-js.scss
fala/assets-src/sass/_fala-results.scss
fala/assets-src/sass/main.scss
fala/templates/adviser/_results.html

- Changes the focus colour to the new yellow for links on the Google map, including:
- - the full-screen button;
- - the zoom buttons;
- - the terms and conditions link.
- Changes the colours of the active state in the results panel.
- Changes the tag to GDS colours.
- Changes the list of legal area to a bulleted list.
- Changes the distance to GDS black.
- Removed the superfluous focus colour state for the whole div.
- Changes the next and previous navigation controls consistent with the MoJ Design System

LGA-1039 map and results styling

---

fala/apps/adviser/forms.py
fala/templates/adviser/search.html
fala/templates/base.html
fala/templates/macros/element.html
fala/templates/macros/forms.html

- Moved the error summary to the top of the page (just below the Google translate control)
- Added a margin to the Google translate control to separate it from the error box.
- New JS function for error finding.
- Added in error summary for field errors.
- Field error location swapped with hint text.
- Marked the postcode in the hint text as no-translate.  
(Google translate was "translating" SW1H 9JA to 9JA SW1H)
- Marked the hint text as `| safe` for the above

LGA-1035 Error message style

---

fala/apps/adviser/forms.py
fala/templates/adviser/_results.html
fala/templates/base.html

- If a postcode is entered that is of the Isle of Man, Jersey or Guernsey, a specific error message informs the user that this service is not for those areas.
- Similar error message introduced for Northern Ireland.

LGA-525 Crown Dependency Specific Error Messages

---

fala/assets-src/sass/main.scss
fala/templates/base.html
fala/templates/generic-py-base.html

Replaces defunct cookie banner with new banner with accept and reject options.
Sets a cookie for 1 month if approved.  
Moves GA startup functions into new function.
If no GA ID - this function only prints something to the console.
Runs said function on page load only if cookies are approved.
Runs said function when cookies approved.
Changes (JS enabled) cookie link at the bottom to re-shew the cookie banner, set focus and scroll to it.  
Removed duplicated GA functions

LGA-1041 New Cookie Banner and GA by consent.  

---

.circleci/config.yml
fala/apps/adviser/forms.py
fala/templates/adviser/search.html
fala/templates/base.html
fala/templates/macros/element.html
fala/templates/macros/forms.html

- Added error highlighting for input boxes.
- Added error text for global errors (visible above postcode input and screen reader only above org input)
- Restricted red line for non-global errors to relevant field only.
- Error summary for no answer changed to link to both postcode and org boxes.

LGA-1191 error styling

---

kubernetes_deploy/development/deployment.yml
kubernetes_deploy/production/deployment.yml
kubernetes_deploy/production/ingress.yml
kubernetes_deploy/staging/deployment.yml
kubernetes_deploy/staging/ingress.yml

Updates to the new kubernetes resource API versions ready for the kubernetes server upgrade.
The server uses all versions it supports interchangeably, so deploying with this now is effectively a no-op but gets us ready for the next version.

LGA-1282 - Upgrade kubernetes resource api versions

---

fala/apps/adviser/views.py
fala/settings/base.py
kubernetes_deploy/production/deployment.yml
kubernetes_deploy/staging/deployment.yml
requirements/base.txt

Switches from Raven library to Sentry SDK, and starts passing an `environment` tag.
Uses the same secret name for DSN, so merging this PR will still send data to the old Sentry instance, eg https://sentry.service.dsd.io/mojds/staging-fala/issues/63232/ (triggered via a deliberate exception-causing path that was temporarily added to the view code)
Once this is merged, we can reroute errors to the new Sentry instance by updating the secret.
The new instance has been tested on staging by using a different secret name in order to route to it before the existing secret is changed eg https://sentry.io/organizations/ministryofjustice/issues/1901244840/?project=5433781&query=is%3Aunresolved

LGA-1426 - Sentry SDK

---

kubernetes_deploy/production/deployment.yml

Properly sets the `ENVIRONMENT` env var to "production" on production, rather than "staging"

LGA-1454 - Fix environment name in production settings

---

conf/uwsgi.ini
kubernetes_deploy/production/deployment.yml

Add preStop lifecycle hook and terminationGracePeriod to allow enough time for uwsgi finish processing requests
Changes explained:
- **die-on-term** - respect the convention of shutting down the instance
- **preStop** - Sleep for 30 seconds. Called before receiving SIGTERM. Aim here is to sleep enough time for the current requests to finish.
- **terminationGracePeriodSeconds** - Amount of time kubernetes waits before sending us the SIGKILL signal.
Important note from the [kubernetes documentation ](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace)on how the preStop and terminationGracePeriodSeconds interact:
> It’s important to note that this(_terminationGracePeriodSeconds_) happens in parallel to the preStop hook and the SIGTERM signal. …

LGA-1465 - uwsgi graceful termination workaround 

---

fala/apps/adviser/views.py
fala/assets-src/sass/main.scss
fala/settings/base.py
fala/settings/local.example.py
fala/templates/base.html
fala/templates/generic-py-base.html

- Adds a graphical indicator and badge to display the current working environment 
- Changes the name of the badge on production (and eventually live) from **Alpha** to **Beta**
The name of the badge on production (and eventually live) has been changed to **Beta** from **Alpha** due to changes discussed outside of the ticket.
**You will have to recreate your `local.py` file from `local.example.py` in order for these changes to take fully effect.** This is because we do not want the default environment to be set to dev if for example, we was on a production environment and the production env var was removed, we would be seeing a badge of dev on production. 
Not creating your `local.py` will cause your badge to be **Unknown** instead of **Development**

Feature/LGA-1395 Environment Badge

---

fala/assets-src/sass/_fala-results.scss

Adds focus styling to the Google Map - missed off the previous PR for LGA-1510

LGA-1510 Map focus colour (missing from previous deployment)

---

.circleci/config.yml
Dockerfile
kubernetes_deploy/production/ingress.yml
kubernetes_deploy/staging/ingress.yml

- Add external DNS annotations to FALA ingress.
- Update circleci python image used for testing from circleci/python:3.7 to cimg/python:3.7 otherwise it was failing to build uwsgi
- Fix base image to debian buster
- There has been a new release of debian(bullseye) since the creation of the Dockerfile
- This release is incompatible with node8 that is built for this project
- LGA-1909 has been created to capture the need to upgrade node for this project
Cloud Platforms is migrating from a self-hosted Kubernetes cluster to EKS.
As part of this migration, the load balancer will need to stop directing traffic to the existing instance of our service and start directing it to an instance of our service running on the new cluster. This cutover will be controlled by us, by annotations on our …

LGA-1897 - Add external DNS annotations to FALA ingress

---

.circleci/config.yml
kubernetes_deploy/staging-live1/collect-static-cronjob.yml
kubernetes_deploy/staging-live1/collect-static-job.yml
kubernetes_deploy/staging-live1/dashboard.yml
kubernetes_deploy/staging-live1/deployment.yml
kubernetes_deploy/staging-live1/ingress.yml
kubernetes_deploy/staging-live1/service.yml

Deploy staging to new live cluster
Create new `kubernetes_deploy/staging-live1` deployment files and deploy to live-1 cluster
Deploy existing `kubernetes_deploy/staging` deployment files to new live cluster
Set `kubernetes_deploy/staging-live1` ingress weight to 0% so that it does not receive any traffic
Set `kubernetes_deploy/staging` ingress weight to 100% so that it receives all of the traffic

LGA-1929 - Deploy staging to live

---

.circleci/config.yml

Remove live-1 staging deployment.
Use new laa-fala context for non live-1 deployments

LGA-1962 - Remove live-1 staging deployment

---

kubernetes_deploy/production/ingress.yml

Update ingress for production namespace
In addition to https://github.com/ministryofjustice/fala/pull/130 but updates the production namespace which was forgotten in that PR

LGA-2126 - Update ingress for production namespace

---

kubernetes_deploy/production/ingress.yml

Update ingress name for production namespace
In addition to https://github.com/ministryofjustice/fala/pull/130 but updates the production namespace which was forgotten in that PR

LGA-2126 - Update ingress name for production namespace

---

kubernetes_deploy/development/collect-static-cronjob.yml
kubernetes_deploy/production/collect-static-cronjob.yml
kubernetes_deploy/staging/collect-static-cronjob.yml

- Changes the cronjob schedule, for getting new AWS Keys to every 4 hours, from every 24 hours.
The reason for this change is that tokens are generated that were expiring at 00:07 the following day. The old implementation was getting a token at 00:00, which was set to expire in 7 minutes. The new implementation regularly gets a new token so that the client will not be given an outdated token.
To see the issue please visit: [Staging](https://staging.find-legal-advice.justice.gov.uk/?postcode=SW1)
The issue was temporarily fixed on live by manually running the script to get a new token, thus fixing the issue (Until 00:07 tomorrow)

LGA 2704: Fix issue where markers are not not correctly being loaded on the map

---

fala/templates/adviser/search.html
fala/templates/ajax-base.html

Restore logic for using an ajax base file for ajax requests
This was wrongfully removed on https://github.com/ministryofjustice/fala/pull/166 as part of a Django upgrade

LGA-2712 - Restore logic for using an ajax base file for ajax requests

---

kubernetes_deploy/development/collect-static-cronjob.yml
kubernetes_deploy/production/collect-static-cronjob.yml
kubernetes_deploy/staging/collect-static-cronjob.yml

Remove deprecated batch/v1beta1 API version of CronJob
[The batch/v1beta1 API version of CronJob is no longer served as of v1.25.](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125)

LGA-2727 - Remove deprecated batch/v1beta1 API version of CronJob

---

fala/apps/adviser/context_processors.py
fala/apps/adviser/views.py
fala/settings/base.py
fala/templates/404.html
fala/templates/500.html
fala/templates/base.html
fala/templates/feedback/index.html
fala/templates/generic-py-base.html
kubernetes_deploy/production/deployment.yml

Remove GA3, Use Google Tag Manager to call GA4.
Hardcoded ID as simpler and won't change. Using existing cookie framework to implement.
Using inline script as per existing approach, but this may be something of a refactor at some point to put all scripts in files.

LGA-2757 Remove GA3 and add GTM

---

.github/CODEOWNERS

This means:
* CCQ are notified about PRs that need reviewing.
* CCQ reviews count towards being able to merge the PR (according to the branch protection that "Requires review from Code Owners")
I'm leaving Team 1 on the codeowners list, for the time being, for a handover period, or emergency help.

Add CCQ to CODEOWNERS

---

package-lock.json

This PR reformats the package-lock.json according to our agreed version of Node & NPM (Node 10.24 & npm 6.14.12). All I did was:
```
npm install
```
and it converts it from `lockfileVersion: 3` back to 1.
I believe it got converted to the newer format accidently in a [recent PR](https://github.com/ministryofjustice/fala/pull/195/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L22) that upgraded govuk-frontend, where I believe the dev had a much newer version of Node&NPM installed.
Restoring the format should make things easier for devs to see actual changes to the lock file.
In the course of this, some packages are upgraded.

package-lock.json formatted for Node 10.24 & npm 6.14.12

---

.circleci/config.yml
.pre-commit-config.yaml

When CircleCI runs pre-commit, that runs *pip-compile*, this PR improves the output to show any error.
Before this PR it displayed the full compiled file:
which is not particularly helpful for seeing the problem. So we add `-q` for quiet.
With this PR, it displays the 'git diff', which shows the modification, which is what pre-commit considers an error:
We can see the problem now - the version of `black`.
(We see that pip-compile has updated `black`, so the author of the PR has forgotten to run pip-compile. So the build is right to fail.)
These examples are from testing on this branch: https://app.circleci.com/pipelines/github/ministryofjustice/fala?branch=dependabot%2Fpip%2Frequirements%2Fgenerated%2Fblack-24.3.0 
The alternative scenario is that someone is on the command-line and they …

pip-compile error messages improved, 

---

.gitignore
docker-compose.yml
fala/settings/base.py
fala/settings/local.example.py
kubernetes_deploy/development/deployment.yml
kubernetes_deploy/production/deployment.yml
kubernetes_deploy/staging/deployment.yml

Adding a feature flag for our up and coming FALA development upgrade work. 
Though "false" is used as a boolean in the kubenetes deployment.yml, it can be anything we like, it can even be an empty. All we care about if the string true is visible or not.
- [EL-1451](https://dsdmoj.atlassian.net/browse/EL-1451)
[EL-1451]: https://dsdmoj.atlassian.net/browse/EL-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

EL-1451 feature flag

---

.pre-commit-config.yaml
requirements/generated/requirements-dev.txt
requirements/generated/requirements-production.txt
requirements/source/requirements-dev.in

7.4.1 is the latest release.
There's no particular drive to do this upgrade, other than the desire to be generally up to date.
The upgrade results in subtle formatting changes to the generated requirements*.txt, such as:
```
-cla_common
+cla-common
```

Upgrade pip-tools

---

fala/apps/adviser/tests/test_search_view_function.py

Fix up tests after the data refresh - some counts changed 
This was caused by a lack of pyvcr (or similar) - maybe we should start using it?

Fix up tests after data in staging refreshed

---

fala/apps/adviser/tests/test_search_view_function.py
fala/apps/adviser/views.py
fala/templates/adviser/results.html
fala/templates/macros/element.html

This pull request implements the grey 'change search' on the results.html. The box shows the user their current search parameters and also have a button that allows them to go back to the search.html and perform a new search.
When they change their search, their previous search params are populated on the search page for them to edit.
When they do not add postcode or org, this param will not render in the grey box on results.html
To translate the categories on the results.html to nice strings, we have had to use the code which gets them from the LAALAA api. ~~My only concern is we will be hitting this API a lot more to get the categories.~~
~~I couldn't see a simple way to just store whatever is returned as the categories from the API (was thinking something like Ruby's `@variable ||=` …

EL-1435: Display params on results page and allow return to search

---

fala/templates/generic-py-base.html

- FALA name in header links to root url path not main-content 
- Purposely not behind feature flag, so will apply to current FALA. 
- Similar to how CCQ does it.

EL-1513 - FALA name links to root url path

---

fala/templates/adviser/search.html
fala/templates/base.html

- In order to work with form input data, which is either not redacted, means we give more data to google or violates our CSP we can use [dataLayer variables](https://developers.google.com/tag-platform/tag-manager/datalayer)
- This PR therefore creates those [dataLayer variables which we can then interrogate in GA4](https://www.analyticsmania.com/post/data-layer-variable/) 

El-1447: Add `dataLayer` variables for GA4

---

fala/apps/adviser/templatetags/adviser_extras.py
fala/apps/adviser/tests/test_adviser_extras.py
fala/templates/adviser/results.html

Pass the org name into the google map link. We are also looking at the office type (namely if it is outreach or not) to know how to construct the google map link. 
~~I'm wondering if this is the right thing to do - it sort of made some listings look worse. Sometimes the business name on google and the name we have don't match, which leads to a partial match search (not the end of the world.)~~
~~In some cases adding the name renders the business un-findable in Google. This seems to be the case for businesses operation outside of communal workspaces (where multiple businesses share the same address). We have rubbish data in LAALAA that doesn't always match Google very well.~~
Update: we've now added in the office type as a condition too, to help us generate better links for some offices.

EL-1527: Add org name to google map link

---

fala/templates/base.html

- This PR updates when the dataLayer Script is called - it builds upon this [PR ](https://github.com/ministryofjustice/fala/pull/265)
- We are using dataLayer in order to get user input (i.e postcode, organisation name, checkboxes). This creates a JSON object that GA4 and TagManager can pick out, so we can use it for custom reporting. 
This PR helps to populate the get the following Variables, Triggers & Tags in TagManager:
- Data Layer Variable - Categories clicked by User
- Data Layer Variable - Organisation entered by User
- Data Layer Variable - Postcode entered by User
- Custom Event - formSubmission
- GA4 event - form_submission
Best way to review that this PR is populating the above is to:
- Pull down this branch.
- Run the branch in a local server on your machine.
- Enter the …

EL-1447- Update when dataLayer Script is called

---

.circleci/config.yml
helm_deploy/laa-fala/values/fala-production.yaml

Helm prod deploy was failing due to an incorrect naming convention of the ingress. This PR fixes the name and also add a distinct name for the helm production deploy.

rename ingress to comply with naming requirements

---

helm_deploy/laa-fala/values/fala-production.yaml

Helm production deploys are not working, possibly because the service account name on production is different to the one on staging. Thsi change fixes the name for the prod service account

update service account name for production

---

fala/apps/adviser/templatetags/adviser_extras.py
fala/apps/adviser/views.py
fala/templates/adviser/results.html

While working on EL-1536, it was noticed that our view has too many parameters. Changing this was considered outside of scope for that ticket, so this PR makes that change independently. It then turned out the the code has duplication and confusing behaviour, so this has 2 things worth putting into the codebase 
This change doesn't have a specific ticket associated with it

DRY up category selection, moving methods

---

fala/apps/adviser/templatetags/adviser_extras.py
fala/apps/adviser/views.py
fala/templates/adviser/results.html

This reverts commit 732a8f0ba62f71e9fa97a36515ba8b8ece88f3bb.
This reverts the bug with the page links losing the category search behaviour

Revert "DRY up category selection, moving methods (#290)"

---

fala/apps/adviser/templatetags/adviser_extras.py
fala/apps/adviser/tests/test_search_view_function.py
fala/apps/adviser/views.py
fala/templates/adviser/results.html

Fix bug - pagination links pointed at non-category search always (even on a category search) so second and subsequent pages displayed non-filtered information

EL-1627: Refactor category methods, without breaking pagination links

---

.github/actions/delete-uat-release/action.yml
.github/workflows/delete_uat_release.yml

Fixes some terminology in the GA yml files
Updates the trigger for deletion

EL-1621 update trigger for Github Action STG deletion

---

.circleci/config.yml

UAT job is deploying to staging on main. Stop this from happening.

EL-1619: Set UAT deploy workflow to only run on branches and not main

---

fala/apps/adviser/tests/page_objects.py
fala/templates/adviser/results.html

- translating postcode, organisation & categories fields in grey box on results page
- not translating what the user input on search screen

EL-1626: Translating postcode, organisation & categories fields in grey box on results page

---

fala/apps/adviser/tests/page_objects.py
fala/apps/adviser/tests/test_pagination_playwright.py
fala/templates/adviser/results.html

Fix flakey test where we were using result count to deduce if the filters remained applied correctly.

EL-1684: Fix flakey pagination test

---

fala/playwright/setup.py

Create a new browser context for each test. Turns out we were not using Playwright correctly for multi-page scenarios, as the 'browser' object was actually a shortcut, so that browser.new_page() called browser.new_context().new_page() which creates issues when wanting to check state between pages (specifically cookies) 

Create a new browser context for each test

---

fala/apps/laalaa/api.py

Sort FALA categories by name not by abbreviation code

EL-1561 Sort FALA categories by name not by abbreviation code

---

.circleci/config.yml
bin/deploy.sh

Convert ECR image tag from branch name to commit hash, so that each commit has a separate ECR image
It appears that using the branch name for the tag results in multiple images with the same tag, where cloud platform seems to spin up an arbitrary image associated with the tag

EL-1697 use commit hash as part of ECR image tag

---

.circleci/config.yml
bin/deploy.sh

use branch hash in ECR tag name to prevent wrong tag being used during UAT. Doesn't work with production k8s deployment, but that is now unused

EL-1697 use branch hash in ECR tag name

---

docs/virtual-env.md
fala/apps/adviser/forms.py
fala/apps/adviser/tests/page_objects.py
fala/apps/adviser/tests/test_search_page_journeys_playwright.py
fala/apps/adviser/views.py
fala/playwright/setup.py

- form validation happens when the data is cleaned, i.e. form validation, form errors, form cleaned
- `def clean(self)` is the method triggering form validation, so have abstracted that into `AdviserSearchForm` form class
- have not made the form do a post, as suggested by the ticket, as this would not be feasible to do

EL-1507: Pre-populated-url

---

.github/actions/delete-uat-release/action.yml

Removing delete command for PVC. No longer needed as we now use Helm Deploy. Will remove errors after every PR merge going forward.
-[El-1640](https://dsdmoj.atlassian.net/browse/EL-1640)

EL-1640 Removing delete pvc command. Not required

---

kubernetes_deploy/production/ingress.yml

removes the cert from the k8s deploy as it is not valid for the host name we use here
-[El-1716](https://dsdmoj.atlassian.net/browse/EL-1716)

EL-1716 remove certificate

---

fala/templates/adviser/results.html

- add padding to bottom of `<ul>`, to make link more readable
- n/a

EL-1599: Padding on categories list

---

fala/apps/adviser/LICENSE.md

[Jira ticket](https://dsdmoj.atlassian.net/browse/EL-1602)
Adds the standard MIT license used across all of LAA digital services

add MIT License to the service

---

fala/assets-src/sass/main.scss
fala/templates/adviser/results.html

- update where items are shown on card listing
- update css to accommodate for new spacings
- n/a

EL-1812: Update listing card styling

---

fala/templates/adviser/results.html

- add hidden text of org name, for the 'View on map (opens in new tab)' links.

EL-1921: Add organisation name as a hidden text of the 'View on map' link

---

fala/templates/adviser/results.html

Adds a back link that returns the user to the appropriate single category search page

EL-1967 Add back link to single category search results

---

fala/apps/adviser/tests/test_category_search_results.py
fala/apps/adviser/tests/test_fala_views_and_functions.py
fala/templates/adviser/results.html

fix an issue where the back button would not render and broke the single category search
add tests to check visibility of the back link

Bugfix: Single Category Search back link

---

.circleci/config.yml

Removes the staging deploy approval process for FALA staging env
Why? this was before we had multi env deployments so Staging had to be kept in a steady state,
We no longer require this step.
The production approval step can remain for the xmas period and afterwards we will comment it out as per CCQ

EL-2010: Remove staging deploy approval for FALA

---

.circleci/config.yml

adds a requires to staging deployment so the image is built before we deploy

BUGFIX: add requires for staging so deployment does not happen too soon

---

.circleci/config.yml

- make `Deploy Grafana Staging Dashboards` dependant on `build` job
-n/a

EL-2048: Make `Deploy Grafana Staging Dashboards` dependant on `build` job

---

fala/apps/tests/page_objects.py
fala/apps/tests/test_other_regions_playwright.py
fala/apps/tests/test_other_regions_view.py
fala/common/results_view.py
fala/locale/cy/LC_MESSAGES/django.po
fala/playwright/setup.py
fala/templates/adviser/other_region.html
fala/templates/base.html

This pr removes the Change Search button, and adds a back link, to the other_region search results page.
It updates the tests to test for this. It also makes a small change to playwright setup, as I think the OtherRegionPage page_objects were not being loaded correctly.

El 2031 amend change search function

---

fala/apps/tests/test_fala_views_and_functions.py
fala/assets-src/sass/main.scss
fala/common/mixin_for_views.py
fala/templates/adviser/_language_switcher.html
fala/templates/base.html

Adds a "language-switcher" link as per designs.
Do we need to "save" when a user clicks on this link somewhere, or as a cookie?
I haven't added any functionality to change the link content when the user clicks it as I think this is part of the follow up ticket el-1975

el-1974: add language switcher link

---

fala/common/tests/playwright/test_translation_playwright.py
fala/templates/adviser/accessibility_statement.html
fala/templates/adviser/category_search.html
fala/templates/adviser/cookies.html
fala/templates/adviser/other_region.html
fala/templates/adviser/privacy.html
fala/templates/adviser/results.html
fala/templates/adviser/search.html

Hide google translate functionality behind feature flag (if FEATURE_FLAG_WELSH_TRANSLATION enabled don't show google translate div)

el-1976: hide google translate element when welsh feature flag enabled

---

fala/apps/adviser/templatetags/adviser_extras.py
fala/apps/category_search/forms.py
fala/apps/category_search/tests/test_search_view.py
fala/apps/category_search/views.py
fala/common/mixin_for_views.py
fala/common/results_view.py
fala/common/states.py
fala/templates/adviser/_results_heading.html
fala/templates/adviser/category_search.html
fala/templates/adviser/other_region.html
fala/templates/adviser/results.html
fala/urls.py

- CLA will send over a URL which will look like:
- `/check?categories=mat&sub-category=hlpas`
- FALA will now resolve this URL to:
- `/check/family?sub-category=hlpas`
- form will not validate when there is a redirect 
- main category display name (and sub text) is shown on search form, results, & errors states
- handles single and multiple categories 
- back links work with multiple and single categories
- n/a

EL-2006: Handle multiple categories in query param

---

fala/templates/adviser/results.html
fala/templates/adviser/search.html

- if applied, the request URL will no longer include `&search=`
- n/a

EL-2129: Remove redundant query param (`&search=`) from url

---

fala/common/states.py
fala/locale/cy/LC_MESSAGES/django.po

- if applied, this will add translation text for `previous` & `next` pagination links
- n/a

EL-2071: Handle `govuk-frontend pagination component`, in order to get ‘previous’ & ‘next’ text translations

---

docs/virtual-env.md

- If applied, this change will update the `readme.md` to capture decision on not using babel
- n/a

EL-2073: Update `Readme.md` about the use of babel Jinja2 component translations

---

fala/apps/category_search/views.py
fala/common/category_manager.py
fala/common/tests/playwright/test_cookies_page_journeys_playwright.py
fala/locale/cy/LC_MESSAGES/django.po
fala/templates/adviser/category_search.html

Translates category checkbox (and the category on the category search page).
In order that the translations for categories are found, and are not deleted when re-running makemessages, I have had to add the category strings (at the moment as a list in CategoryManager) - I have not been able to think of any way around this? 🤔 

EL-2072: add category translations

---

fala/templates/adviser/cookies.html

Remove debug text added in error as part of ticket to hide google translate functionality when  welsh translations enabled.

Remove debug text added in error

---

fala/locale/cy/LC_MESSAGES/django.po
fala/templates/adviser/category_search.html
fala/templates/adviser/search.html

- If applied, this add 'Error: ' to the page title, when there is a form validation error.
- [Uservision recommendation ](https://uv3202-moj-fala.uservisionaccessibility.co.uk/error-is-not-indicated-in-the-page-title-observation.html)

EL-2203: Indicate errors in page titles

---

fala/common/mixin_for_views.py

- If applied this removes the aria labels for language links, as per the recommendation from uservision
- [Uservision finding](https://uv3202-moj-fala.uservisionaccessibility.co.uk/welsh-toggle-link-not-pronounced-properly-by-screen-readers-observation.html)

EL-2201: Change ARIA label on Welsh link
