ministryofjustice/fala

fala/assets-src/sass/_google-translate.scss, fala/assets-src/sass/main.scss, fala/templates/base.html, package.json
=> added google translate

fala/settings/base.py
=> LGA-452 Flake8 fixes

.circleci/config.yml
Add `pip check` to CI test job to verify dependency compatibility.
=> LGA-438 Add pip check to CI

fala/apps/laalaa/api.py
Add Discrimination and Education categories
=> LGA-787 - Adding Discrimination and Education categories

fala/apps/laalaa/api.py
Put Re-order categories alphabetically
- [] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"
=> Re-order categories alphabetically

fala/templates/base.html
Removes the text about the mandatory gateway as users are not required to go to CLA for education and discrimination cases
I've removed the text - do I need to remove the additional code tags around it?
LGA 790
https://dsdmoj.atlassian.net/browse/LGA-790
=> LGA 790 remove gateway text

kubernetes_deploy/production/deployment.yml, kubernetes_deploy/production/ingress.yml, kubernetes_deploy/production_live_0/ingress.yml
Removes the production hostname from the live-0 ingress and adds it to the live-1 ingress
=> LGA-904 - live-1 cutover

.circleci/config.yml, Dockerfile, fala/apps/adviser/views.py, package-lock.json, package.json, requirements/base.txt
Upgrade to Django 2.2
Update python from 3.4 to 3.7 (django 2.2 requires at least 3.5)
=> LGA-943 - Upgrade to Django 2.2

fala/templates/adviser/search.html
Removed the origanisation type from the front-end.
=> LGA-868 Removed FALA organisation type options from front-end

fala/assets-src/sass/main.scss, fala/templates/adviser/search.html, fala/templates/base.html, fala/templates/external.html, fala/templates/generic-py-base.html
Updates header and footer to new style
Moved the remote templates generic-py-base.html  and external.html from the "mojular-templates" nodejs package into the project so they can be edited.
Removed grey background from form area.
=> LGA-1032 header and footer

fala/templates/ajax-base.html
It adds in a div to a file which is missing.  It also adds in a missing paragraph.
=> LGA-1069 layout stuff missed from previous ticket

fala/assets-src/sass/main.scss, fala/templates/404.html, fala/templates/500.html, fala/templates/ajax-base.html, fala/templates/generic-py-base.html
Introduces error attribute to identify error messages for CSS styling.
New CSS for the red error bar.
Removed duplicate HTML.
Added in GDS ⅔ width div.
Smart quotes on 500 page.
=> LGA-1063 error pages

fala/assets-src/scripts/find-legal-adviser.js
Changed the if statement from firing when the map isn't present to firing if an alert (a warning message like "no matches") is present.  
=> LGA-1116 Changed criteria for jumping to postcode entry box

fala/templates/500.html, fala/templates/generic-py-base.html
Removed erroneous references to CLA and replaced them with FALA
=> LGA-1316 Erroneous mentions of CLA in FALA

fala/assets-src/sass/_fala-results-js.scss, fala/assets-src/sass/_fala-results.scss, fala/assets-src/scripts/find-legal-adviser.js, requirements/lint.txt
- Focus link colour and highlighting for map and list of results
- Expanding map area
- Black version thingy
=> LGA-1388 Update FALA with latest LARP changes

package.json
- Update govuk-frontend library
=> LGA-1378 Update GDS styles

fala/apps/adviser/context_processors.py, fala/apps/adviser/views.py, fala/settings/base.py
- Makes the current environment available for all pages to use
=> LGA-1493 - Pass ENVIRONMENT variable in context processor

fala/assets-src/sass/_fala-results-js.scss, fala/assets-src/sass/main.scss, fala/templates/adviser/search.html
- Adjusts map height to be slightly more suited for low result situations.
- Adds class name for styles
- Moves inline style to new class name in CSS file
- Adds clear float to form
=> LGA-1571 Form clears float and map height

package.json
Updates the GDS version to 3.10.2
=> LGA-1549: Update GDS styles

.circleci/config.yml
Remove image push to DSD registry
=> Remove image push to DSD registry

.circleci/config.yml, kubernetes_deploy/production-1/collect-static-cronjob.yml, kubernetes_deploy/production-1/collect-static-job.yml, kubernetes_deploy/production-1/dashboard.yml, kubernetes_deploy/production-1/deployment.yml, kubernetes_deploy/production-1/ingress.yml, kubernetes_deploy/production-1/service.yml, kubernetes_deploy/production/ingress.yml
Deploy production namespace also the new live cluster
=> LGA-1930 production deployment to new live cluster

kubernetes_deploy/production-live1/ingress.yml, kubernetes_deploy/production/ingress.yml
Send all traffic to the new live cluster.
Requires https://github.com/ministryofjustice/fala/pull/111 to be merged in first
=> LGA-1944 Send all traffic to the new live cluster

.circleci/config.yml
Remove live-1 production deployment
=> LGA-1963 - Remove live-1 production deployment

requirements/jenkins.txt
Remove unused jenkins requirement file
=> Remove unused jenkins requirement file

fala/apps/adviser/forms.py
Rewording search field to only search postcodes and not 
["LGA-152: Sample title"](https://dsdmoj.atlassian.net/browse/LGA-2448)
=> LGA-2448 updating postcode field lable description to only say postcode

fala/settings/base.py, kubernetes_deploy/production/collect-static-cronjob.yml, kubernetes_deploy/production/collect-static-job.yml, kubernetes_deploy/production/deployment.yml, kubernetes_deploy/staging/collect-static-cronjob.yml, kubernetes_deploy/staging/collect-static-job.yml, kubernetes_deploy/staging/deployment.yml
=> LGA-2583 - Use new irsa service account

fala/templates/base.html
As a dev, I need to change the old google form  survey link with the new survey monkey survey.
[LGA-2653](https://dsdmoj.atlassian.net/browse/LGA-2653)
[LGA-2653]: https://dsdmoj.atlassian.net/browse/LGA-2653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LGA-2653 changing google form to a survey monkey link

.github/CODEOWNERS
Adding individual, to avoid them being added as reviewer for the CCQ repo too
=> Add davidread to CODEOWNERS

.github/CODEOWNERS
So they stop getting notifications
=> Remove Team 1 from CODEOWNERS

.pre-commit-config.yaml, pyproject.toml, requirements/generated/requirements-lint.txt, requirements/source/requirements-lint.in
Might as well be on the latest black
=> Update black and add folder excludes

.circleci/config.yml, .circleci/define_build_environment_variables
Only run FALA tests from end-to-end repo, so that FALA build times are reduced
=> El 1440 only run fala tests

.circleci/config.yml, fala/apps/adviser/forms.py, fala/apps/adviser/laa_laa_paginator.py, fala/apps/adviser/tests/test_laa_laa_paginator.py, fala/apps/adviser/tests/test_search_view_function.py, fala/apps/adviser/views.py, fala/assets-src/sass/main.scss, fala/templates/adviser/results.html, fala/templates/adviser/search.html, fala/templates/base.html, fala/urls.py, requirements/generated/requirements-dev.txt, requirements/source/requirements-dev.in
New results page with pagination
=> EL-1434 new results page with pagination

.circleci/config.yml
Updating CircleCi config to place Behave tests as part of deployment pipeline. 
Depends on [EL-1440](https://dsdmoj.atlassian.net/browse/EL-1440)
-[ El-1470](https://dsdmoj.atlassian.net/browse/EL-1470)
[EL-1440]: https://dsdmoj.atlassian.net/browse/EL-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EL-1470 placing behave job into pipeline deployment order

.circleci/config.yml, kubernetes_deploy/staging/ingress-dashboard.yml, kubernetes_deploy/staging/pods-dashboard.yml
Enable prometheus and grafana dashboards
=> El 1468 grafana dashboards

.circleci/config.yml
Fix the production deploy step 
Deploying grafana only works on staging so don't try it on production deploy
=> EL-1468 follow up - fix prod deploy by using separate grafana deploy

fala/apps/adviser/tests/test_search_view_function.py, fala/assets-src/sass/main.scss, fala/templates/adviser/results.html
Rework results page after UAT comments
=> El 1434 results page rework

docs/virtual-env.md
Add some detail to the readme about running tests
=> NO-TICKET: Update README with test instructions

fala/apps/adviser/templatetags/adviser_extras.py, fala/apps/adviser/tests/test_adviser_extras.py, fala/assets-src/sass/main.scss, fala/templates/adviser/results.html
Add google map link on results page
=> EL-1436 google map link on results page

.circleci/config.yml, .circleci/define_build_environment_variables, kubernetes_deploy/production/deployment.yml, kubernetes_deploy/staging/deployment.yml
Re-enable production deploys after master branch rename
=> Update fala to deploy production from main after branch rename

fala/apps/adviser/forms.py, fala/apps/adviser/regions.py, fala/apps/adviser/tests/test_crown_dependencies_view.py, fala/apps/adviser/tests/test_search_view_function.py, fala/apps/adviser/views.py, fala/templates/adviser/other_region.html, fala/templates/adviser/results.html, fala/templates/adviser/search.html
Add crown dependencies and Northern Ireland / Scotland results page
=> El 1433 crown dependencies results

fala/assets-src/sass/main.scss, fala/templates/adviser/results.html
=> EL-1515 remove awkward padding on results page when distance not present

fala/templates/adviser/search.html, fala/templates/adviser/search_old.html
- Small change, so when a checkbox is clicked we have a meaningful name for it, in our data fro GA.
=> EL-1447: Update checkboxes `id` label

fala/templates/adviser/other_region.html
- To help with tracking how make people interact with this button and see this page in Google Analytics. 
=> EL-1447: Add `id` to change search button

.env.example, fala/apps/adviser/tests/test_search_view_function.py, fala/apps/adviser/views.py, fala/assets-src/sass/main.scss, fala/settings/base.py, fala/templates/adviser/results.html, fala/templates/research_banner.html, kubernetes_deploy/development/deployment.yml, kubernetes_deploy/production/deployment.yml, kubernetes_deploy/staging/deployment.yml
=> EL-1467 Add Research banner

fala/apps/adviser/tests/test_search_view_function.py, fala/apps/adviser/views.py, fala/urls.py
=> Wrapped urlpattern to search page in feature flag condition

docker-compose.yml, docs/virtual-env.md, fala/settings/base.py, run_local.sh
We realised it might be better to rename the new local dev DB as fala_development, and update the README to make the installation steps clearer.
This PR also contains a fix to the docker container setup where we pass in the DB credentials, and also add the migration command to the docker compose file. This is to make the out-the-box experience better.
Noop.
=> NO-TICKET: DB rename and tidy-up

kubernetes_deploy/staging/deployment.yml
Removes IRSA service account after S3 bucket and irsa deleted from cloud platform
This breaks deployment if not done
=> EL-1586 remove irsa service account

fala/templates/base.html
- updating monkey survey link for feedback to a new url link
- Adding in (opens in a new tab) into the url to tell users link opens in a new tab.
[EL-1598](https://dsdmoj.atlassian.net/browse/EL-1598)
[EL-1598]: https://dsdmoj.atlassian.net/browse/EL-1598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> EL-1598 Updated survey link to new survey monkey link

kubernetes_deploy/production/deployment.yml, kubernetes_deploy/staging/deployment.yml, kubernetes_deploy/staging/pods-dashboard.yml
Tweak resources and dashboards - dashboards were showing incorrect data, but resources were also probably too low
=> EL-1496 tweak FALA resources and dashboards

README.md, fala/apps/adviser/views.py, fala/templates/adviser/privacy.html, fala/templates/base.html, fala/templates/footer.html, fala/templates/generic-py-base.html, fala/urls.py
- Add `Privacy` link to footer and extract the footer into its own partial
- N/A
=> EL-1549: Privacy policy

kubernetes_deploy/production/deployment.yml
Removes service account from production deployment
This was missed during other PRs for some reason
=> EL-1586 remove production irsa service account

kubernetes_deploy/development/deployment.yml, kubernetes_deploy/production/deployment.yml
- Turn on the FALA feature flag for `production` & `development`
- Also turned on Survey Monkey link for `production` & `development`
=> EL-1539: Release FALA Refresh - MERGE ONLY ON 25/06/24

Dockerfile-playwright, requirements/generated/requirements-dev.txt, requirements/source/requirements-dev.in
Fix build after playwright 1.44 image pulled by Microsoft
=> Microsoft just broke our build

kubernetes_deploy/development/deployment.yml, kubernetes_deploy/production/deployment.yml, kubernetes_deploy/staging/deployment.yml
Change settings from true to enabled for staging and prod deploys
=> update feature flag settings

.circleci/config.yml
Required.
https://dsdmoj.atlassian.net/browse/EL-1618
makes staging approval and deploy only available to main branch. 
=> EL-1618 update deployment pipeline

fala/apps/adviser/views.py
Remove unused code missed during removal of old FALA code during https://dsdmoj.atlassian.net/browse/EL-1452
This code was missed during the removal of the old FALA code
=> Remove unused code missed during removal of old FALA code

.circleci/config.yml, helm_deploy/laa-fala/values/fala-staging.yaml, kubernetes_deploy/staging/ingress.yml
Setting ground work for switching to deploying staging with helm. 
=> EL-1619: Deploy staging with helm

.circleci/config.yml, helm_deploy/laa-fala/values/fala-staging.yaml
Correct ingress and remove legacy staging job
=> EL-1619: Second attempt staging helm deploy

fala/templates/generic-py-base.html
Updates jquery version to 3.5.0
=> EL-1647 upgrade jquery to fix sec vulns

fala/apps/adviser/tests/page_objects.py, fala/apps/adviser/tests/test_cookies_page_journeys_playwright.py, fala/apps/adviser/views.py, fala/assets-src/sass/main.scss, fala/playwright/setup.py, fala/templates/adviser/cookies.html, fala/templates/footer.html, fala/templates/generic-py-base.html, fala/urls.py
- create new cookies page
- add content
- update footer
- update base
- setup specific playwright setup in cookies test case, rather than using existing set-up
- need to use `context` rather than `page`
- use `wait_for_selector`
- added in `wait_for_load_state()` because the page was not loaded fully, before test did it's thing.
- update wording of test and add a few more scenarios.
- n/a
=> EL-1690: Create Cookie Policy Page

.circleci/config.yml, helm_deploy/laa-fala/values/fala-production.yaml, kubernetes_deploy/production/ingress.yml
FALA production helm deploy
Circle CI changes appear to have already been made
=> EL-1655 FALA production helm deploy

.circleci/config.yml, bin/deploy.sh
This reverts commit eaee554110202676897fedd67a064e2222033aaf.
Revert EL-1697 as it doesnt work with non-helm deploy
=> Revert "EL-1697 use commit hash as part of ECR image tag (#338)"

fala/apps/adviser/forms.py, fala/apps/adviser/tests/test_other_regions_view.py
Adds scotland region into form clean up function. Updated and refactored code and unit tests.
Try manually testing UAT branch for confidence. 
[UAT Link](https://el-1698-unsupporte-fala-staging.cloud-platform.service.justice.gov.uk)
- [specific postcode"](https://dsdmoj.atlassian.net/browse/EL-1698)
=> EL-1698 addressed LAALAA API being called for scotland postcode region

fala/templates/adviser/search.html
We introduced a bug where the font size on Cat of Law checkbox heading was too big. This fixes it.
=> EL-1711: Fix font size on Cat of Law

fala/templates/adviser/_cookie_banner.html
We've gone and done the classic faux pas.
=> EL-1718: Remove word 'test' from cookie banner

fala/apps/adviser/forms.py, fala/apps/adviser/tests/test_fala_views_and_functions.py, fala/apps/adviser/tests/test_search_page_journeys_playwright.py, fala/templates/adviser/results.html, fala/templates/adviser/search.html
- update content as per accessibility report
- update tests
- display categories alphabetically and lowercase except HLPAS
=> EL-1686: Update content based on accessibility report

fala/apps/adviser/tests/test_search_page_journeys_playwright.py, fala/assets-src/sass/main.scss, fala/assets-src/scripts/cookies.js, fala/templates/adviser/results.html, fala/templates/macros/element.html, gulpfile.js
- add conditional for `h1` based on results
- remove html macro
- remove redundant css
- update tests
- fix typos in `cookies.js` & `gulpfile.js`
- n/a
=> EL-1687: 'No results' hierarchy

fala/templates/adviser/accessibility_statement.html, fala/templates/adviser/cookies.html, fala/templates/adviser/other_region.html, fala/templates/adviser/privacy.html, fala/templates/adviser/results.html
add HTML titles for:
- search results
- search results: other region
- cookies
- privacy
- accessibility statement
- N/A
=> EL-1574: Add HTML titles

fala/assets-src/scripts/google_tag_manager_data_layer.js, fala/templates/adviser/search.html, fala/templates/base.html, fala/templates/macros/forms.html, gulpfile.js
- amend `id` for one of the questions
- remove `novalidate` in form
- adjust the JS and run only when cookies are allowed
- n/a
=> EL-1751: `form_submission` event not firing in GA4

fala/apps/adviser/tests/page_objects.py, fala/apps/adviser/tests/test_other_regions_playwright.py, fala/apps/adviser/tests/test_search_page_journeys_playwright.py, fala/playwright/setup.py, fala/templates/adviser/search.html
- update label on organisation filed
- update tests
- n/a
=> EL-1570: Update Organisation name field

requirements/generated/requirements-dev.txt, requirements/generated/requirements-production.txt, requirements/source/requirements-base.in
- update `sentry-sdk` using pre-commit
- this ticket will then close off [this dependabot ticket](https://github.com/ministryofjustice/fala/pull/320)
=> EL-1790: update `sentry-sdk` using pre-commit

fala/templates/adviser/search.html
- update the size of the postcode input field
- n/a
=> EL-1828: Postcode field, postcode sized

run_local.sh
- replace `docker-compose` to `docker compose`
- n/a
=> EL-1816: Update shell script docker commands

.env.example, docker-compose.yml, fala/apps/adviser/tests/test_fala_views_and_functions.py, fala/apps/adviser/views.py, fala/settings/base.py, fala/templates/base.html, fala/templates/maintenance_mode.html, helm_deploy/laa-fala/templates/_envs.tpl, helm_deploy/laa-fala/values/fala-production.yaml, helm_deploy/laa-fala/values/fala-staging.yaml, helm_deploy/laa-fala/values/fala-uat.yaml
- new maintenance mode view & feature flag
- add environment variables
- pass through variable
- not a new url route, just a template which overrides all other templates.
=> EL-1639: Create a maintenance mode page for FALA

.env.example, helm_deploy/laa-fala/values/fala-production.yaml, helm_deploy/laa-fala/values/fala-staging.yaml, helm_deploy/laa-fala/values/fala-uat.yaml
=> EL-1826 turn off research banner

.env.example
- remove conflicts that were left in
- n/a
=> Remove conflicts that were accidentally left in

fala/apps/adviser/templatetags/adviser_extras.py, fala/assets-src/sass/main.scss, fala/templates/adviser/results.html, fala/templates/adviser/search.html
- content change to search page
- content change to results page
=> EL-1919: Content improvements

fala/templates/base.html
=> EL-1841: Add meta-description

fala/apps/adviser/forms.py, fala/apps/adviser/laa_laa_paginator.py, fala/apps/adviser/models.py, fala/apps/adviser/tests/test_fala_views_and_functions.py, fala/apps/adviser/tests/test_other_regions_playwright.py, fala/apps/adviser/tests/test_pagination_playwright.py, fala/apps/adviser/tests/test_results_page_journeys_playwright.py, fala/apps/adviser/tests/test_search_page_journeys_playwright.py, fala/apps/adviser/views.py, fala/apps/laalaa/api.py, fala/playwright/setup.py
See other PR for details. This is post rebase.
https://github.com/ministryofjustice/fala/pull/384
=> EL-1902: 404 page post rebase

fala/apps/adviser/tests/page_objects.py, fala/apps/adviser/tests/test_fala_views_and_functions.py, fala/apps/adviser/tests/test_single_category_search_page_journeys_playwright.py, fala/assets-src/sass/main.scss, fala/templates/adviser/results.html, fala/templates/adviser/single_category_search.html
- add exit button, with id, and condition to show it
- add css to align with google translate
- n/a
=> EL-1820: Exit page button

fala/apps/adviser/tests/test_fala_views_and_functions.py, fala/apps/adviser/tests/test_single_category_search_page_journeys_playwright.py, fala/templates/adviser/_results_heading.html, fala/templates/adviser/results.html, fala/templates/adviser/single_category_search.html
For single category search, modify the H1 accordingly.
=> EL-1984: Add category to results h1

fala/apps/constants/category_manager.py
Update heading on immigration and asylum landing page.
=> el-2009: Update heading to display immigration or asylum

fala/apps/adviser/views.py, fala/apps/category_search/forms.py, fala/apps/category_search/views.py, fala/common/base_form_components.py, fala/common/results_view.py
- separate out the relevant forms for the relevant folders
- extract out the common elements amongst the forms
- remove redundant constants
-  n/a
=> EL-2046: Separate existing `forms.py` into correct folder structure

fala/apps/tests/test_fala_views_and_functions.py
Fix our test data which is blocking our pipeline.
=> Fix test data

fala/apps/category_search/tests/test_results_view.py, fala/common/results_view.py, fala/common/states.py, fala/templates/adviser/results.html
- add conditional string based on url
- add in `BACK_LABEL` text for translation
- n/a
=> EL-2083: Fix pagination links for Mini FALA check

fala/locale/cy/LC_MESSAGES/django.po, fala/templates/base.html
- If applied, this change will update our missing Welsh translations
- I have updated the `urls.py` so that UAT reviewers can check the translations. This is temporary change which will be removed before merging.
=> EL-2074: Match the Welsh words to English words, Part 2

fala/assets-src/sass/main.scss, fala/common/results_view.py, fala/templates/adviser/_language_and_navigation.html, fala/templates/adviser/_language_and_navigation_other_region.html, fala/templates/adviser/_language_switcher.html, fala/templates/adviser/category_search.html, fala/templates/adviser/other_region.html, fala/templates/adviser/results.html, fala/templates/base.html
If applied, this change will update the layout for navigational and language links
- update to CSS
- 2 templates on for normal pages, one for other region
- re-do logic of feature flag, so it is easier to remove, when feature is released
- n/a
=> EL-2117: Update layout for navigational & language links (part 2)

helm_deploy/laa-fala/values/fala-staging.yaml
- If applied, this change will enable `single_category_search` on staging
- n/a
=> EL-2084: Enable `FEATURE_FLAG_SINGLE_CATEGORY_SEARCH_FORM` in Staging

fala/locale/cy/LC_MESSAGES/django.po, fala/templates/404.html, fala/templates/500.html, fala/templates/adviser/_language_and_navigation_error_page.html, fala/templates/base.html, fala/urls.py, helm_deploy/laa-fala/values/fala-uat.yaml
- If applied, this will add a new custom 404 route and add a partial to 404.html
- n/a
=> EL-2132: Add translation widget to 404, 500 and maintenance mode pages

fala/common/mixin_for_views.py, fala/common/tests/playwright/test_cookies_page_journeys_playwright.py, fala/locale/cy/LC_MESSAGES/django.po, fala/settings/base.py, fala/templates/adviser/cookies.html
- If applied, this updates the FALA cookie policy
- n/a
=> EL-2104: Update cookie policy

fala/locale/cy/LC_MESSAGES/django.po, fala/templates/adviser/category_search.html, fala/templates/adviser/search.html
adds new content around the postcode field and adds welsh translations of the same
=> EL-2137 add content changes around postcode

helm_deploy/laa-fala/values/fala-staging.yaml
- If applied, this will turn on the Welsh feature flag for staging
- n/a
=> EL-2141: Turn Welsh feature flag on in staging

fala/locale/cy/LC_MESSAGES/django.po, fala/templates/base.html
added translation for a hidden element
=> EL-2198 translate skip to main content

fala/templates/base.html
=> EL-2199 set the lang to welsh

fala/locale/cy/LC_MESSAGES/django.po, fala/templates/adviser/cookies.html
Adds translation to the page title for cookies
there were some numbering changes made, probably because the new translation is at the top of the page so all translations below get re-ordered, so the PO file looks like it has more changes than would be expected, but these are mainly in comments that will not affect the actual file.
=> EL-2198 add translation for cookies

README.md
- If applied, this updates the readme.md for `mini-fala` removal epic.
- n/a
=> EL-2151: Update FALA `readme.md` to include CHECK Search URLs

fala/common/footer_views.py, fala/locale/cy/LC_MESSAGES/django.po, fala/templates/adviser/cookies.html
makes the link function likke a back buttton
=> EL-2200 Cookies back link

helm_deploy/laa-fala/values/fala-production.yaml
- If applied, this change enables Welsh translations in FALA production
- n/a
=> EL-1978: Enable Welsh translations on FALA production

fala/apps/adviser/templatetags/adviser_extras.py, fala/apps/adviser/tests/playwright/test_results_page_journeys_playwright.py, fala/apps/adviser/tests/playwright/test_search_page_journeys_playwright.py, fala/apps/adviser/tests/test_results_view.py, fala/apps/category_search/tests/playwright/test_end_to_end_journeys_playwright.py, fala/apps/category_search/tests/test_results_view.py, fala/assets-src/sass/main.scss, fala/common/test_utils/playwright/page_objects.py, fala/common/tests/playwright/test_other_regions_playwright.py, fala/common/tests/playwright/test_pagination_playwright.py, fala/common/tests/playwright/test_translation_playwright.py, fala/locale/cy/LC_MESSAGES/django.po, fala/templates/adviser/_language_and_navigation.html, fala/templates/adviser/_language_and_navigation_results_page.html, fala/templates/adviser/_results_heading.html, fala/templates/adviser/results.html
- If applied, this updates the result page styling and associated tests.
- associated tests and translations also updated.
=> EL-2270: Update results page styling for accessibility

helm_deploy/laa-fala/values/fala-production.yaml
- If applied, this turns on mini-fala for production
- n/a
=> EL-2139: Turn on FEATURE_FLAG_SINGLE_CATEGORY_SEARCH_FORM in Production
